name: Deploy Website

on:
  push:
    branches:
      - main  # Hoặc nhánh mà bạn muốn theo dõi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Node.js (nếu bạn sử dụng Node cho build step)
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies (nếu có bước cài đặt dependencies)
      run: npm install

    - name: Build the website (tùy thuộc vào framework bạn sử dụng)
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./.github/workflows/
